#ifndef __LEARNING_GEM5_P2S_HH__
#define __LEARNING_GEM5_P2S_HH__

#include <cstdint>
#include <deque>
#include <string>
#include <vector>
#include "mem/port.hh"
#include "params/P2S_L.hh"
#include "params/P2S_R.hh"
#include "params/P2S_R_T.hh"
#include "sim/clocked_object.hh"

namespace gem5
{

struct P2SWritePayload
{
    uint64_t arrayAddr;
    uint64_t bitSlice;
};

    struct DMALPayload{
        // row = 1;
        // byte_per_row = 512;
        // baseAddr_Array = 0;
        uint32_t offset;
        uint64_t baseAddr_DRAM;
    };
    struct DMARPayload{

    };
    struct DMARTPayload{
        uint32_t byte_per_row;
        uint64_t baseAddr_DRAM;
    };
    class P2S_L : public ClockedObject {
        private:
            // to interact with scheduler
            class CPUSidePort : public ResponsePort
            {
                private:
                    P2S_L *owner;

                public:
                    CPUSidePort(const std::string& name, P2S_L *owner);
                    bool sendPacket(PacketPtr pkt);

                // there are three modes: Atomic, Functional and Timing
                protected:
                    Tick recvAtomic(PacketPtr pkt) override {panic("recvAtomic unimplemented.");}
                    void recvFunctional(PacketPtr pkt) override;
                    bool recvTimingReq(PacketPtr pkt) override;
                    void recvRespRetry() override;
                    AddrRangeList getAddrRanges() const override;
            };
            // to interact with DMA and Cache Bank
            class MemSidePort : public RequestPort
            {
                private:
                    // corresponds to each direct port
                    enum class PortID {DMA, CB};
                    P2S_L *owner;
                    PortID portID;
                public:
                    MemSidePort(const std::string& name, P2S_L *owner);
                    void sendPacket(PacketPtr pkt);

                protected:
                    bool recvTimingResp(PacketPtr pkt) override;
                    void recvReqRetry() override;
            };
            // direct port
            CPUSidePort instPort;
            MemSidePort DMAPort;
            MemSidePort CacheBankPort;

            // gem5 transaction identity for requests generated by P2S_L
            RequestorID requestorId;
            PacketPtr pendingControlPkt = nullptr;

            bool datapathDone = false;

            void completeControlRequest();
            void retryControlResponse();

            // variables
            uint64_t base_dram_addr;
            uint64_t base_picAddr;
            uint64_t pic_write_ptr;
            uint32_t next_row_offset_elem;
            uint32_t next_row_offset_dram;
            uint8_t _L_block_row;
            uint8_t _L_block_row_ptr;
            uint8_t next_slice_offset_pic;
            uint8_t precision;
            uint8_t bit_ptr;

            uint8_t dmaRow;

            // buffer to store data accessed from DMA
            std::vector<std::vector<uint8_t>> regArray; // 8 * 8

            // write bank queue
            std::deque<PacketPtr> bitSliceQueue;
            // events
            EventFunctionWrapper dmaReadEvent;
            EventFunctionWrapper bitSliceEvent;
            EventFunctionWrapper writeEvent;
        protected:
        public:
            Port &getPort(
                const std::string &if_name,
                PortID idx = InvalidPortID) override;
            P2S_L(const P2S_LParams &params);
            bool handleRequest(PacketPtr pkt);
            uint64_t extractBits(const std::vector<std::vector<uint8_t>> &arr, uint8_t bit);
            void processDMAReadEvent();
            void processBitSliceEvent();
            void processWriteEvent();
    };

    class P2S_R : public ClockedObject
    {
      private:
        class CPUSidePort : public ResponsePort
        {
          private:
            P2S_R *owner;

          public:
            CPUSidePort(
                const std::string &name,
                P2S_R *owner);

            bool sendPacket(PacketPtr pkt);

          protected:
            Tick recvAtomic(PacketPtr pkt) override
            {
                panic("P2S_R recvAtomic unimplemented");
                return 0;
            }

            void recvFunctional(PacketPtr pkt) override;
            bool recvTimingReq(PacketPtr pkt) override;
            void recvRespRetry() override;
            AddrRangeList getAddrRanges() const override;
        };

        class MemSidePort : public RequestPort
        {
          private:
            P2S_R *owner;

            bool dmaSide;

          public:
            MemSidePort(
                const std::string &name,
                P2S_R *owner,
                bool dmaSide);

            void sendPacket(PacketPtr pkt);

          protected:
            bool recvTimingResp(PacketPtr pkt) override;
            void recvReqRetry() override;
        };

        CPUSidePort instPort;
        MemSidePort DMAPort;
        MemSidePort CacheBankPort;

        RequestorID requestorId;
        uint32_t wordlineNums;

        // Request parameters.
        uint64_t base_arrayID_to_store = 0;
        uint32_t nCols = 0;
        uint32_t nRows = 0;
        uint8_t precision = 0;
        uint8_t bufNum = 0;

        uint32_t next_row_offset_bytes = 0;
        uint64_t dramAddr = 0;

        std::vector<uint8_t> relative_offset_buf = std::vector<uint8_t>(7);

        std::vector<uint8_t> arrayID_offset = std::vector<uint8_t>(8);


        std::vector<std::vector<uint8_t>> mem0 =
            std::vector<std::vector<uint8_t>>(64,std::vector<uint8_t>(128, 0));

        std::vector<std::vector<uint8_t>> regArray =
            std::vector<std::vector<uint8_t>>(64,std::vector<uint8_t>(8, 0));

        std::deque<PacketPtr> bitSliceQueue;

        uint32_t curBlockColPtrGlobal = 0;
        uint32_t curBlockNCols = 0;
        uint64_t curBlockDramBaseAddr = 0;

        uint32_t dmaRow = 0;

        uint32_t curBufColPtrInBlock = 0;
        uint32_t curBufNCols = 0;
        uint32_t loadBufferRow = 0;

        uint32_t curEnqBlockInBufColPtr = 0;
        uint8_t bit_ptr = 0;

        bool active = false;

        // Scheduler relinquishes the request packet when timing request
        // acceptance succeeds.  P2S_R owns it until operation completion
        PacketPtr pendingControlPkt = nullptr;

        // Set when no more output slices will be produced
        bool datapathDone = false;

        void completeControlRequest();
        void retryControlResponse();

        PacketPtr blockedDmaPkt = nullptr;

        EventFunctionWrapper dmaReadEvent;
        EventFunctionWrapper loadBufferEvent;
        EventFunctionWrapper bitSliceEvent;
        EventFunctionWrapper writeEvent;

        bool handleDMAResponse(PacketPtr pkt);
        void retryDMARequest();

      public:
        Port &getPort(
            const std::string &if_name,
            PortID idx = InvalidPortID) override;

        P2S_R(const P2S_RParams &params);

        bool handleRequest(PacketPtr pkt);

        void get_array_relatice_offset(
            std::vector<uint8_t> &offset,
            uint8_t numBuf);

        // Restore separated asynchronous P2S_R stages
        void processDMAReadEvent();
        void processLoadBufferEvent();
        void processBitSliceEvent();

        void processWriteEvent();

        uint64_t extractBits_R(
            const std::vector<std::vector<uint8_t>> &arr,
            uint32_t column,
            uint8_t bit,
            uint32_t dim = 8);
    };

    class P2S_R_T : public ClockedObject{
        private:
            class CPUSidePort : public ResponsePort
            {
                private:
                    P2S_R_T *owner;

                public:
                    CPUSidePort(const std::string& name, P2S_R_T *owner);
                    bool sendPacket(PacketPtr pkt);

                // there are three modes: Atomic, Functional and Timing
                protected:
                    Tick recvAtomic(PacketPtr pkt) override {panic("recvAtomic unimplemented.");}
                    void recvFunctional(PacketPtr pkt) override;
                    bool recvTimingReq(PacketPtr pkt) override;
                    void recvRespRetry() override;
                    AddrRangeList getAddrRanges() const override;
            };
            // to interact with DMA and Cache Bank
            class MemSidePort : public RequestPort
            {
                private:
                    // corresponds to each direct port
                    enum class PortID {DMA, CB};
                    P2S_R_T *owner;
                    PortID portID;
                public:
                    MemSidePort(const std::string& name, P2S_R_T *owner);
                    void sendPacket(PacketPtr pkt);

                protected:
                    bool recvTimingResp(PacketPtr pkt) override;
                    void recvReqRetry() override;
            };
            // direct port
            CPUSidePort instPort;
            MemSidePort DMAPort;
            MemSidePort CacheBankPort;

            RequestorID requestorId;
            uint32_t wordlineNums;
            // request params
            uint64_t base_arrayID_to_store;
            uint32_t nCols;
            uint32_t nRows;
            uint8_t precision;     
            uint8_t bufNum;
            uint32_t next_row_offset_bytes;
            uint64_t dramAddr;

            uint32_t dmaRow = 0;
            uint8_t bit_ptr = 0;
            uint32_t row_store_ptr = 0;

            // since each element is 8 bit, arrayID_offset has 8 elements corresponding to each bit
            std::vector<uint8_t> relative_offset_buf = std::vector<uint8_t>(7);
            std::vector<uint8_t> arrayID_offset = std::vector<uint8_t>(8);

            // Buffer Array 
            std::vector<uint64_t> bufArray = std::vector<uint64_t>(8);               // nBuf = 8, busWidth=64 bit
            std::vector<uint8_t> bufArrayOutReFormat = std::vector<uint8_t>(64);    // bitline=64
            // write bank queue
            std::deque<PacketPtr> bitSliceQueue;

            bool active = false;
            bool datapathDone = false;
            PacketPtr pendingControlPkt = nullptr;

            void completeControlRequest();
            void retryControlResponse();
            EventFunctionWrapper dmaReadEvent;
            EventFunctionWrapper bitSliceEvent;
            EventFunctionWrapper writeEvent;
        protected:
        public:
            Port &getPort(
                const std::string &if_name,
                PortID idx = InvalidPortID) override;
            P2S_R_T(const P2S_R_TParams &params);

            bool handleRequest(PacketPtr pkt);

            void processDMAReadEvent();
            void processBitSliceEvent();
            void processWriteEvent();

            uint64_t extractBits_R_T(const std::vector<uint8_t> &buf,uint8_t bit);

            void get_array_relatice_offset(std::vector<uint8_t> &offset,uint8_t numBuf);
    };
}

#endif // __LEARNING_GEM5_P2S_HH__
